### 5 input for 1 hidden layer and 3 hidden layer and 1 main function ..total input:15 ,hidden layer 3 func main func then y_pred

In [9]:
#crate model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        
        )
    def forward(self,features):
        out=self.network(features)
    
        
        return out
    

In [3]:
#create dataser
features=torch.rand(10,5)

#create moDEL
model=Model(features.shape[1])


#call model
model(features)

tensor([[0.4545],
        [0.4279],
        [0.4864],
        [0.4787],
        [0.4616],
        [0.4564],
        [0.4543],
        [0.4864],
        [0.4864],
        [0.4781]], grad_fn=<SigmoidBackward0>)

In [4]:
#show model weifghts
model.linear1.weight

Parameter containing:
tensor([[-0.1175, -0.1611,  0.3259, -0.4330, -0.0639],
        [ 0.2584, -0.1926, -0.0298, -0.0235, -0.3046],
        [-0.3008,  0.1294,  0.2957, -0.1592,  0.3748]], requires_grad=True)

In [6]:
model.linear2.weight

Parameter containing:
tensor([[-0.1254, -0.3612, -0.3825]], requires_grad=True)

In [7]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00