In [4]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out
    

In [5]:
#creaet  dataset 
features=torch.rand(10,5)


#creae model
model=Model(features.shape[1])

#call model for forward pass
#model.forward(feature)
model(features)



tensor([[0.5262],
        [0.5475],
        [0.4820],
        [0.4718],
        [0.4511],
        [0.4353],
        [0.4891],
        [0.4652],
        [0.5219],
        [0.4849]], grad_fn=<SigmoidBackward0>)

In [7]:
#show model weighjts
model.linear.weight

Parameter containing:
tensor([[-0.0963,  0.3884, -0.2310, -0.0588, -0.2605]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([0.1618], requires_grad=True)

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00