In [2]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))


2.5.1
12.1
True
NVIDIA GeForce RTX 3050 6GB Laptop GPU


### Creating a Tensor

In [3]:
#using empty:
torch.empty(2,3)

tensor([[-9.6348e-35,  1.5933e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
# check type
x = torch.empty(2,3)
print(type(x))

<class 'torch.Tensor'>


In [5]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.4564, 0.2576, 0.4517],
        [0.8677, 0.9402, 0.5444]])

In [8]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
#other ways

#arange
print('using arange->',torch.arange(0,10,2))

#using linspace
print("using linspace->",torch.linspace(0,10,10))

#using eye
print("using eye->\n",torch.eye(5))


#using full
print("using full->",torch.full((3,3),5))

using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [11]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[4885642872688,             0,             0],
        [            0,             0,             0]])

In [14]:
torch.zeros_like(x
                 )

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Mathematical Operations


1. scalar Operation

In [17]:
x=torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [18]:
#addition
x+2

#subtraction
x-2

#multiplication
x*3

#division
x/3

#int division
(x*100)//3

#mod
((x*100)//3)%2

#power
x**2



tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

2. Element Wise Operation

In [19]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print("a->\n",a)
print("b->\n",b)

a->
 tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
b->
 tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [20]:
#add
a+b

#sub
a-b
#mul
a*b

#div
a/b

#power
a **b

#mod
a%b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [21]:
c=torch.tensor([1,-2,3,-4])

In [22]:
#  abs -aBSOLUTE VALYUE
torch.abs(c)

tensor([1, 2, 3, 4])

In [23]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [24]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [25]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [26]:
#cell
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [27]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [28]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction operation

In [35]:
e=torch.randint(size=(2,3),low=1,high=10,dtype=torch.float)
e

tensor([[7., 4., 9.],
        [3., 7., 6.]])

In [36]:
#sum
torch.sum(e)


#sum along cloums
torch.sum(e,dim=0)


#sum along rows
torch.sum(e,dim=1)



tensor([20., 16.])

In [37]:
#mean
torch.mean(e,dim=0)

tensor([5.0000, 5.5000, 7.5000])

In [38]:
torch.median(e)

tensor(6.)

In [39]:
torch.max(e)

tensor(9.)

In [40]:
torch.min(e)

tensor(3.)

In [41]:
#standard deviation
torch.std(e)

tensor(2.1909)

In [42]:
#variance
torch.var(e)

tensor(4.8000)

In [43]:
#arg max
torch.argmax(e)

tensor(2)

In [44]:
#marg min
torch.argmin(e)

tensor(3)

## 4 Matrix operation

In [47]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

print("f->\n",f)
print("g->\n",g)

f->
 tensor([[5, 9, 9],
        [7, 5, 9]])
g->
 tensor([[8, 9],
        [7, 9],
        [2, 6]])


In [48]:
#torch multiplication

torch.matmul(f,g)

tensor([[121, 180],
        [109, 162]])

In [49]:
torch.matmul(g,f)

tensor([[103, 117, 153],
        [ 98, 108, 144],
        [ 52,  48,  72]])

In [50]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [51]:
#transpose

torch.transpose(f,0,1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [54]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[4., 0., 8.],
        [4., 7., 2.],
        [3., 8., 5.]])

In [56]:
#determint
torch.det(h)

tensor(164.0000)

In [57]:
#inverse
torch.inverse(h)

tensor([[ 0.1159,  0.3902, -0.3415],
        [-0.0854, -0.0244,  0.1463],
        [ 0.0671, -0.1951,  0.1707]])

## Comparison Operator

In [58]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print("i->\n",i)
print("j->\n",j)

i->
 tensor([[6, 2, 9],
        [5, 0, 4]])
j->
 tensor([[2, 7, 1],
        [1, 5, 4]])


In [62]:
#greater then 
i>j
#less then
i<j
#equal to 
i==j
#not equal to
i!=j
#grather then equal to 
#less then qual to 

tensor([[ True,  True,  True],
        [ True,  True, False]])

6. Special Function


In [71]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float)
k

tensor([[2., 5., 6.],
        [1., 4., 5.]])

In [72]:
#log
torch.log(k)

tensor([[0.6931, 1.6094, 1.7918],
        [0.0000, 1.3863, 1.6094]])

In [73]:
#exp
torch.exp(k)

tensor([[  7.3891, 148.4132, 403.4288],
        [  2.7183,  54.5981, 148.4132]])

In [74]:
#sqrt

torch.sqrt(k)

tensor([[1.4142, 2.2361, 2.4495],
        [1.0000, 2.0000, 2.2361]])

In [75]:
#sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9933, 0.9975],
        [0.7311, 0.9820, 0.9933]])

In [76]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.7311, 0.7311, 0.7311],
        [0.2689, 0.2689, 0.2689]])

In [77]:
#relu
torch.relu(k)

tensor([[2., 5., 6.],
        [1., 4., 5.]])

## Implace Operation

In [78]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print("m->\n",m)
print("n->\n",n)

m->
 tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])
n->
 tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])


In [79]:
m+n

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [80]:
m.add_(n)  ## inplace operation

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [81]:
m

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [82]:
n

tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])

In [83]:
torch.relu(m)

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [84]:
m.relu_()  ## inplace operation

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

In [85]:
m

tensor([[1.4047, 0.8966, 1.3610],
        [1.6774, 1.5705, 0.5734]])

### Copying a  Tensor

In [86]:
a=torch.rand(2,3)
a

tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [87]:
b=a

In [91]:
b  #pointing to same memory location

tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [89]:
id(a)

2156418819600

In [92]:
id(b)

2156418819600

In [93]:
b=a.clone()

In [94]:
id(a)

2156418819600

In [95]:
id(b)

2156291056128

## tensor Operation in GPU

In [97]:
torch.cuda.is_available()

True

In [98]:
device=torch.device("cuda")

In [99]:
#creating a new tnesor on GPU
torch.rand(2,3,device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [101]:
#moving existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682]])

In [103]:
d=a.to(device) #function to move tensor to GPU

In [104]:
b+5

tensor([[5.9436, 5.3904, 5.2499],
        [5.3206, 5.9753, 5.7582]])

In [108]:
#  COPIIED EXAMPLE TO CHECK CPU EXECUTION VS GPU EXECUTION
import time
#defoine the size fo the matrics
size=10000

#create a random matrics oon CPU
matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

#Measure time on CPU
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time()-start_time
print(f"Time taken on CPU: {cpu_time:4f} seconds")

#move matrics to GPU
matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

#measure time on GPU
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time=time.time()-start_time
print(f"Time taken on GPU: {gpu_time:4f} seconds")


Time taken on CPU: 10.005648 seconds
Time taken on GPU: 0.000000 seconds


## Reshping Tensor

In [111]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [113]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [114]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [125]:
b=torch.rand(2,3,4)
print(b.shape)


torch.Size([2, 3, 4])


In [126]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [128]:
#unsqueeze
b = torch.randn(2, 3)     # [2, 3]
b = b.unsqueeze(0)         # [1, 2, 3]
print(b.shape)


torch.Size([1, 2, 3])


In [129]:
#squuexe
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [131]:
import numpy as np

In [132]:
#convert tensor to numpy
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [133]:
b=a.numpy()
b

array([1, 2, 3])

In [134]:
type(b)

numpy.ndarray

In [138]:
#numpy to tensor
c=np.array([1,2,3])
c

array([1, 2, 3])

In [137]:
torch.from_numpy(c)

tensor([1, 2, 3])