In [2]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))


2.5.1
12.1
True
NVIDIA GeForce RTX 3050 6GB Laptop GPU


### Creating a Tensor

In [3]:
#using empty:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# check type
x = torch.empty(2,3)
print(type(x))

<class 'torch.Tensor'>


In [5]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.7059, 0.7926, 0.9060],
        [0.9766, 0.0070, 0.1204]])

In [8]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
#other ways

#arange
print('using arange->',torch.arange(0,10,2))

#using linspace
print("using linspace->",torch.linspace(0,10,10))

#using eye
print("using eye->\n",torch.eye(5))


#using full
print("using full->",torch.full((3,3),5))

using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [11]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[2269336700784,             0,             0],
        [            0,             0,             0]])

In [15]:
torch.zeros_like(x
                 )

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Mathematical Operations


1. scalar Operation

In [19]:
x=torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [21]:
#addition
x+2

#subtraction
x-2

#multiplication
x*3

#division
x/3

#int division
(x*100)//3

#mod
((x*100)//3)%2

#power
x**2



tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

2. Element Wise Operation

In [23]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print("a->\n",a)
print("b->\n",b)

a->
 tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])
b->
 tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])


In [24]:
#add
a+b

#sub
a-b
#mul
a*b

#div
a/b

#power
a **b

#mod
a%b

tensor([[0.5277, 0.2472, 0.1394],
        [0.4235, 0.0169, 0.0056]])

In [25]:
c=torch.tensor([1,-2,3,-4])

In [26]:
#  abs -aBSOLUTE VALYUE
torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [29]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [30]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [31]:
#cell
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [32]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [33]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction operation

In [36]:
e=torch.randint(size=(2,3),low=1,high=10)
e

tensor([[7, 2, 1],
        [1, 4, 6]])

In [ ]:
#sum