In [5]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out
    

In [6]:
# import torch
# import torch.nn as nn
# class Model(nn.Module):
#     def __init__(self,num_features):
#         super().__init__()
#         self.linear=nn.linear(num_features,1)
#         self.sigmoid=nn.sigmoid()
#     def forward(self,features):
#         out=self.linear(features)
#         out=self.sigmoid(out)
#         return out
    

In [7]:
#creaet  dataset 
features=torch.rand(10,5)


#creae model
model=Model(features.shape[1])

#call model for forward pass
#model.forward(feature)
model(features)



tensor([[0.5435],
        [0.6032],
        [0.5526],
        [0.5457],
        [0.5149],
        [0.4980],
        [0.5957],
        [0.5754],
        [0.5465],
        [0.5614]], grad_fn=<SigmoidBackward0>)

In [8]:
#show model weighjts
model.linear.weight

Parameter containing:
tensor([[0.0509, 0.3873, 0.1430, 0.0628, 0.1239]], requires_grad=True)

In [9]:
model.linear.bias

Parameter containing:
tensor([-0.1862], requires_grad=True)

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00