##  Trainning Pipeline

#### Today objective
1. building a simple neural network* 
2. dataset:- Breast canceer dataset*
3. main goal:- code to create a neural network


### Steps to Follow

1. Load the dataset
2. Basic Preprocessing
3. Training Process
   1. Creating the model
   2. Forward pass
   3. Loss calculation
   4. Backpropagation
   5. Parameter update
4. Model Evaluation


In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [4]:
df.size

18777

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [8]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)


In [9]:
#scaling
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [10]:
x_train

array([[-0.34721604, -0.82348893, -0.32084912, ..., -0.19996262,
        -1.45418401, -0.70867314],
       [ 1.71459079,  0.24287743,  1.66257514, ...,  0.70715797,
        -0.57961798,  0.39068684],
       [-0.41201568, -0.4493253 , -0.44176878, ..., -0.8952188 ,
        -0.35859129, -0.83945812],
       ...,
       [-1.05706667, -0.99186257, -1.02970324, ..., -0.33085586,
         0.16932856,  0.66976778],
       [-1.34454145, -1.58584734, -1.33520698, ..., -0.8000929 ,
        -0.73703986, -0.35517062],
       [-0.86561318, -0.60834484, -0.90237441, ..., -1.13234865,
        -0.84357791, -0.73275071]], shape=(455, 30))

In [11]:
y_train

284    B
517    M
325    B
328    M
75     M
      ..
258    M
196    M
426    B
21     B
428    B
Name: diagnosis, Length: 455, dtype: object

In [12]:
#Label Encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,

In [14]:
type(y_train)

numpy.ndarray

In [15]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0])

In [16]:
# Numpy arrays to Pytorch tensors
x_train_tensor=torch.from_numpy(x_train).float()
x_test_tensor=torch.from_numpy(x_test).float()

y_train_tensor=torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor=torch.from_numpy(y_test).float().unsqueeze(1)

In [17]:
x_train_tensor

tensor([[-0.3472, -0.8235, -0.3208,  ..., -0.2000, -1.4542, -0.7087],
        [ 1.7146,  0.2429,  1.6626,  ...,  0.7072, -0.5796,  0.3907],
        [-0.4120, -0.4493, -0.4418,  ..., -0.8952, -0.3586, -0.8395],
        ...,
        [-1.0571, -0.9919, -1.0297,  ..., -0.3309,  0.1693,  0.6698],
        [-1.3445, -1.5858, -1.3352,  ..., -0.8001, -0.7370, -0.3552],
        [-0.8656, -0.6083, -0.9024,  ..., -1.1323, -0.8436, -0.7328]])

# defineing the model


In [18]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
        
        
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

    def loss_function(self, y_pred, y):
        
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        # print(f"epoch {loss}")
        return loss
        
        
        
        

In [19]:
loss_function=nn.BCELoss()

### Impotrant Parameter

In [20]:
learning_rate=0.1
epochs=25

## Trainign pipeline

In [21]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
# create model 
model=MySimpleNN(x_train_tensor.shape[1])
# model.weights
#define loop
#define optimoizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):
    
    
    

    #forward pass
    y_pred=model(x_train_tensor)
    # print(y_pred)


    #loss pass
    loss=loss_function(y_pred,y_train_tensor)
    # print(f'Epoch:{epoch+1},Loss:{loss.item()}')
    
    #cleargrads
    #backeard pass
    optimizer.zero_grad()
    loss.backward()
    
    
    #parameter update
    # with torch.no_grad():
        
    #     model.linear.weight-=learning_rate*model.linear.weight.grad
    #     model.linear.bias-=learning_rate*model.linear.bias.grad
    optimizer.step()
    #zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    
    #print loss in each epocj
    print(f'Epoch:{epoch+1},Loss:{loss.item()}')

model parameters before training <generator object Module.parameters at 0x00000202EC7E23B0>
Epoch:1,Loss:0.47633808851242065
Epoch:2,Loss:0.4086269438266754
Epoch:3,Loss:0.36376670002937317
Epoch:4,Loss:0.33135151863098145
Epoch:5,Loss:0.30654376745224
Epoch:6,Loss:0.2867727279663086
Epoch:7,Loss:0.27053573727607727
Epoch:8,Loss:0.25689011812210083
Epoch:9,Loss:0.24521158635616302
Epoch:10,Loss:0.23506835103034973
Epoch:11,Loss:0.22615112364292145
Epoch:12,Loss:0.21823175251483917
Epoch:13,Loss:0.21113771200180054
Epoch:14,Loss:0.20473577082157135
Epoch:15,Loss:0.19892117381095886
Epoch:16,Loss:0.19361020624637604
Epoch:17,Loss:0.18873505294322968
Epoch:18,Loss:0.18424005806446075
Epoch:19,Loss:0.18007904291152954
Epoch:20,Loss:0.1762133687734604
Epoch:21,Loss:0.17261040210723877
Epoch:22,Loss:0.1692422330379486
Epoch:23,Loss:0.16608504951000214
Epoch:24,Loss:0.1631181687116623
Epoch:25,Loss:0.16032366454601288


#

In [27]:
model.linear.weight

Parameter containing:
tensor([[ 0.3658,  0.0519,  0.2764,  0.0735,  0.1567,  0.2089,  0.1283,  0.2417,
          0.0202, -0.0109,  0.3411, -0.1337,  0.0468,  0.1715,  0.0928,  0.1576,
          0.0371,  0.0392, -0.1102, -0.1252,  0.2830,  0.3359,  0.2930,  0.3795,
          0.2519,  0.1435, -0.0083,  0.3482,  0.1625, -0.0424]],
       requires_grad=True)

In [28]:
model.linear.bias

Parameter containing:
tensor([-0.1744], requires_grad=True)

## Evaluation

In [29]:
#model evlauation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
  
    
print(y_pred)

Accuracy: 0.8771929740905762
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
     