##  Trainning Pipeline

#### Today objective
1. building a simple neural network* 
2. dataset:- Breast canceer dataset*
3. main goal:- code to create a neural network


### Steps to Follow

1. Load the dataset
2. Basic Preprocessing
3. Training Process
   1. Creating the model
   2. Forward pass
   3. Loss calculation
   4. Backpropagation
   5. Parameter update
4. Model Evaluation


In [1]:
import numpy as np
import pandas as pd

import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.size

18777

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [7]:
#train test split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)


In [8]:
#scaling
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [9]:
x_train

array([[ 1.14835338, -0.19464011,  1.0591639 , ...,  0.63753269,
         0.48288606, -0.81921171],
       [-1.11387642, -0.44249263, -1.09826888, ..., -0.89312585,
         0.23857157,  0.24960247],
       [ 0.7226201 , -0.1427091 ,  0.68399327, ...,  0.49103651,
        -0.15783275, -0.652479  ],
       ...,
       [-0.64918715, -0.45901613, -0.67791642, ..., -0.35471463,
         0.3129985 , -0.77954083],
       [-0.59075317, -0.1191041 , -0.63273459, ..., -0.96592086,
        -0.04457437, -0.16090497],
       [-0.27075756,  1.37981356, -0.33259809, ..., -0.82818425,
        -0.75001225, -0.90545277]], shape=(455, 30))

In [10]:
y_train

186    M
222    B
167    M
393    M
7      M
      ..
506    B
524    B
293    B
346    B
457    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
#Label Encoding
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,

In [13]:
type(y_train)

numpy.ndarray

In [14]:
y_test

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0])

In [15]:
# Numpy arrays to Pytorch tensors
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)

y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [16]:
x_train_tensor

tensor([[ 1.1484, -0.1946,  1.0592,  ...,  0.6375,  0.4829, -0.8192],
        [-1.1139, -0.4425, -1.0983,  ..., -0.8931,  0.2386,  0.2496],
        [ 0.7226, -0.1427,  0.6840,  ...,  0.4910, -0.1578, -0.6525],
        ...,
        [-0.6492, -0.4590, -0.6779,  ..., -0.3547,  0.3130, -0.7795],
        [-0.5908, -0.1191, -0.6327,  ..., -0.9659, -0.0446, -0.1609],
        [-0.2708,  1.3798, -0.3326,  ..., -0.8282, -0.7500, -0.9055]],
       dtype=torch.float64)

# defineing the model


In [17]:
class MySimpleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    def forward(self,x):
        z=torch.matmul(x,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    def loss_function(self, y_pred, y):
        
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        # print(f"epoch {loss}")
        return loss
        

### Impotrant Parameter

In [18]:
learning_rate=0.1
epochs=25

## Trainign pipeline

In [19]:
# create model 
model=MySimpleNN(x_train_tensor)
model.weights
#define loop
for epoch in range(epochs):
    
    
    

    #forward pass
    y_pred=model.forward(x_train_tensor)
    # print(y_pred)


    #loss pass
    loss=model.loss_function(y_pred,y_train_tensor)
    # print(f'Epoch:{epoch+1},Loss:{loss.item()}')
    
    #backeard pass
    loss.backward()
    
    
    #parameter update
    with torch.no_grad():
        
        model.weights-=learning_rate*model.weights.grad
        model.bias-=learning_rate*model.bias.grad
    #zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    #print loss in each epocj
    print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:3.291666601823332
Epoch:2,Loss:3.1588684967931036
Epoch:3,Loss:3.021867525561233
Epoch:4,Loss:2.885296871336447
Epoch:5,Loss:2.744607897432001
Epoch:6,Loss:2.59191423277549
Epoch:7,Loss:2.4353660936413197
Epoch:8,Loss:2.279711659329854
Epoch:9,Loss:2.125950545068367
Epoch:10,Loss:1.9683090633796614
Epoch:11,Loss:1.817132890767046
Epoch:12,Loss:1.6775866358645573
Epoch:13,Loss:1.5509203472001654
Epoch:14,Loss:1.437921628623361
Epoch:15,Loss:1.3387414392432373
Epoch:16,Loss:1.2495511384870592
Epoch:17,Loss:1.1736615746103183
Epoch:18,Loss:1.1100876632792018
Epoch:19,Loss:1.057187836288015
Epoch:20,Loss:1.0114124550695973
Epoch:21,Loss:0.9741244959189695
Epoch:22,Loss:0.9437115466451486
Epoch:23,Loss:0.9186760426436498
Epoch:24,Loss:0.8977202556704259
Epoch:25,Loss:0.8797915351933241


#

In [20]:
model.weights

tensor([[ 0.3731],
        [ 0.0251],
        [ 0.4348],
        [-0.4950],
        [ 0.0819],
        [-0.0727],
        [-0.3065],
        [ 0.3922],
        [-0.2347],
        [ 0.3150],
        [ 0.0055],
        [ 0.5561],
        [ 0.2751],
        [ 0.4540],
        [ 0.5936],
        [-0.2735],
        [ 0.0902],
        [ 0.3481],
        [-0.1491],
        [-0.1313],
        [-0.1396],
        [-0.2275],
        [-0.0097],
        [ 0.1072],
        [-0.1496],
        [-0.2894],
        [ 0.0638],
        [-0.3377],
        [-0.0621],
        [ 0.0413]], dtype=torch.float64, requires_grad=True)

In [21]:
model.bias

tensor([-0.0972], dtype=torch.float64, requires_grad=True)

## Evaluation

In [22]:
#model evlauation
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
  
    
print(y_pred)

Accuracy: 0.6386580467224121
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
     