In [2]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))


2.5.1
12.1
True
NVIDIA GeForce RTX 3050 6GB Laptop GPU


### Creating a Tensor

In [3]:
#using empty:
torch.empty(2,3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
# check type
x = torch.empty(2,3)
print(type(x))

<class 'torch.Tensor'>


In [5]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
x.type()

'torch.FloatTensor'

In [7]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using rand
torch.rand(2,3)

tensor([[0.4984, 0.4942, 0.9420],
        [0.9917, 0.9507, 0.9731]])

In [10]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
print("using full->\n",torch.full((3,3),5))

using full->
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [13]:
#other ways

#arange
print('using arange->',torch.arange(0,10,2))

#using linspace
print("using linspace->",torch.linspace(0,10,10))

#using eye
print("using eye->\n",torch.eye(5))


#using full
print("using full->",torch.full((3,3),5))

using arange-> tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye->
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [14]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Mathematical Operations


1. scalar Operation

In [20]:
x=torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [21]:
x+2


tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])

In [22]:
x-2


tensor([[-1.2882, -1.2124, -1.5817],
        [-1.0986, -1.0031, -1.2435]])

In [23]:
#addition
x+2

#subtraction
x-2

#multiplication
x*3

#division
x/3

#int division
(x*100)//3

#mod
((x*100)//3)%2

#power
x**2



tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

2. Element Wise Operation

In [27]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print("a->\n",a)
print("b->\n",b)

a->
 tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])
b->
 tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])


In [28]:
#add
a+b

#sub
a-b
#mul
a*b

#div
a/b

#power
a **b

#mod
a%b

tensor([[0.5277, 0.2472, 0.1394],
        [0.4235, 0.0169, 0.0056]])

In [29]:
c=torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [30]:
#  abs -aBSOLUTE VALYUE
torch.abs(c)

tensor([1, 2, 3, 4])

In [31]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [32]:
d=torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [33]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [34]:
#cell
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [35]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [36]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction operation

In [37]:
e=torch.randint(size=(2,3),low=1,high=10,dtype=torch.float)
e

tensor([[7., 4., 1.],
        [7., 5., 4.]])

In [38]:
torch.sum(e,dim=1)


tensor([12., 16.])

In [39]:
#sum
torch.sum(e)


#sum along cloums
torch.sum(e,dim=0)


#sum along rows
torch.sum(e,dim=1)



tensor([12., 16.])

In [40]:
#mean
torch.mean(e,dim=0)

tensor([7.0000, 4.5000, 2.5000])

In [41]:
torch.median(e)

tensor(4.)

In [42]:
torch.max(e)

tensor(7.)

In [43]:
torch.min(e)

tensor(1.)

In [44]:
#standard deviation
torch.std(e)

tensor(2.2509)

In [45]:
#variance
torch.var(e)

tensor(5.0667)

In [46]:
#arg max
torch.argmax(e)

tensor(0)

In [47]:
#marg min
torch.argmin(e)

tensor(2)

## 4 Matrix operation

In [49]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

print("f->\n",f)
print("g->\n",g)

f->
 tensor([[5, 5, 0],
        [4, 3, 8]])
g->
 tensor([[8, 3],
        [3, 5],
        [0, 6]])


In [50]:
#torch multiplication

torch.matmul(f,g)

tensor([[55, 40],
        [41, 75]])

In [51]:
torch.matmul(g,f)

tensor([[52, 49, 24],
        [35, 30, 40],
        [24, 18, 48]])

In [52]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [53]:
f

tensor([[5, 5, 0],
        [4, 3, 8]])

In [54]:
#transpose

torch.transpose(f,0,1)

tensor([[5, 4],
        [5, 3],
        [0, 8]])

In [55]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[4., 0., 8.],
        [4., 7., 2.],
        [3., 8., 5.]])

In [56]:
#determint
torch.det(h)

tensor(164.0000)

In [57]:
#inverse
torch.inverse(h)

tensor([[ 0.1159,  0.3902, -0.3415],
        [-0.0854, -0.0244,  0.1463],
        [ 0.0671, -0.1951,  0.1707]])

## Comparison Operator

In [58]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print("i->\n",i)
print("j->\n",j)

i->
 tensor([[6, 2, 9],
        [5, 0, 4]])
j->
 tensor([[2, 7, 1],
        [1, 5, 4]])


In [59]:
i>j


tensor([[ True, False,  True],
        [ True, False, False]])

In [60]:
#greater then 
i>j
#less then
i<j
#equal to 
i==j
#not equal to
i!=j
#grather then equal to 
#less then qual to 

tensor([[ True,  True,  True],
        [ True,  True, False]])

6. Special Function


In [61]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float)
k

tensor([[4., 1., 1.],
        [2., 4., 7.]])

In [62]:
#log
torch.log(k)

tensor([[1.3863, 0.0000, 0.0000],
        [0.6931, 1.3863, 1.9459]])

In [63]:
#exp
torch.exp(k)

tensor([[  54.5981,    2.7183,    2.7183],
        [   7.3891,   54.5981, 1096.6332]])

In [64]:
#sqrt

torch.sqrt(k)

tensor([[2.0000, 1.0000, 1.0000],
        [1.4142, 2.0000, 2.6458]])

In [65]:
k

tensor([[4., 1., 1.],
        [2., 4., 7.]])

In [66]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.7311, 0.7311],
        [0.8808, 0.9820, 0.9991]])

In [67]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.8808, 0.0474, 0.0025],
        [0.1192, 0.9526, 0.9975]])

In [68]:
k

tensor([[4., 1., 1.],
        [2., 4., 7.]])

In [69]:
#relu
torch.relu(k)

tensor([[4., 1., 1.],
        [2., 4., 7.]])

## Implace Operation

In [70]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print("m->\n",m)
print("n->\n",n)

m->
 tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])
n->
 tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])


In [71]:
m+n

tensor([[1.3114, 0.9096, 1.0504],
        [1.3501, 1.0769, 0.1227]])

In [72]:
m.add_(n)  ## inplace operation

tensor([[1.3114, 0.9096, 1.0504],
        [1.3501, 1.0769, 0.1227]])

In [73]:
m

tensor([[1.3114, 0.9096, 1.0504],
        [1.3501, 1.0769, 0.1227]])

In [74]:
n

tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [75]:
torch.relu(m)

tensor([[1.3114, 0.9096, 1.0504],
        [1.3501, 1.0769, 0.1227]])

In [76]:
m.relu_()  ## inplace operation

tensor([[1.3114, 0.9096, 1.0504],
        [1.3501, 1.0769, 0.1227]])

In [77]:
m

tensor([[1.3114, 0.9096, 1.0504],
        [1.3501, 1.0769, 0.1227]])

### Copying a  Tensor

In [78]:
a=torch.rand(2,3)
a

tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])

In [79]:
b=a

In [80]:
b  #pointing to same memory location

tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])

In [81]:
id(a)

2660876035200

In [82]:
id(b)

2660876035200

In [83]:
b=a.clone()

In [84]:
id(a)

2660876035200

In [85]:
id(b)

2660875472464

## tensor Operation in GPU

In [86]:
torch.cuda.is_available()

True

In [87]:
device=torch.device("cuda")

In [88]:
#creating a new tnesor on GPU
torch.rand(2,3,device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [89]:
#moving existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])

In [90]:
d=a.to(device) #function to move tensor to GPU

In [91]:
b+5

tensor([[5.4890, 5.5887, 5.7340],
        [5.8497, 5.9112, 5.4847]])

In [92]:
#  COPIIED EXAMPLE TO CHECK CPU EXECUTION VS GPU EXECUTION
import time
#defoine the size fo the matrics
size=10000

#create a random matrics oon CPU
matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

#Measure time on CPU
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time()-start_time
print(f"Time taken on CPU: {cpu_time:4f} seconds")

#move matrics to GPU
matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

#measure time on GPU
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time=time.time()-start_time
print(f"Time taken on GPU: {gpu_time:4f} seconds")


Time taken on CPU: 8.183899 seconds
Time taken on GPU: 0.133602 seconds


## Reshping Tensor

In [93]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [94]:
a=torch.rand(2,2,2,2)
a

tensor([[[[0.8487, 0.4059],
          [0.2883, 0.2220]],

         [[0.6423, 0.7098],
          [0.5644, 0.4549]]],


        [[[0.0729, 0.8535],
          [0.9793, 0.0611]],

         [[0.1162, 0.7666],
          [0.8801, 0.4203]]]])

In [95]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[0.8487, 0.4059],
          [0.2883, 0.2220]],

         [[0.6423, 0.7098],
          [0.5644, 0.4549]]],


        [[[0.0729, 0.8535],
          [0.9793, 0.0611]],

         [[0.1162, 0.7666],
          [0.8801, 0.4203]]]])

In [96]:
#flatten
a.flatten()

tensor([0.8487, 0.4059, 0.2883, 0.2220, 0.6423, 0.7098, 0.5644, 0.4549, 0.0729,
        0.8535, 0.9793, 0.0611, 0.1162, 0.7666, 0.8801, 0.4203])

In [97]:
b=torch.rand(2,3,4)
print(b.shape)


torch.Size([2, 3, 4])


In [98]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [99]:
#unsqueeze
b = torch.randn(2, 3)     # [2, 3]
b = b.unsqueeze(0)         # [1, 2, 3]
print(b.shape)


torch.Size([1, 2, 3])


In [100]:
#squuexe
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [101]:
import numpy as np

In [102]:
#convert tensor to numpy
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()
b

In [ ]:
type(b)

In [ ]:
#numpy to tensor
c=np.array([1,2,3])
c

In [ ]:
torch.from_numpy(c)